# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'

name: 'Scheduled Execution'
# Disparar o pipeline manualmente

# regras de disparo (gatilhos/triggers)
# gatilho de execução manual = workflow_dispatch

on:
  schedule:
    # cronograma de execução
    # 1 minuto, 2 hora, 3 dia do mês, 4 mês, 5 dia da semana
    # cron: '0 2 * * *'  # todos os dias às 2 da manhã
    - cron: '0 6 * * 2' # todas as terças-feiras às 6 da manhã

# jobs = tarefas que serão executadas
jobs:
  # nome do job
  e2e-tests:
    # maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/checkout@v4
        with:
          node-version: latest

      # instalação do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências do projeto
      - name: Instalando dependências do projeto
        run: yarn

      # setup playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # execução dos testes
      - name: Executando Testes E2E
        run: yarn run e2e
